const articles = {
  1: {
    title: 'Upaya Pencegahan Hipertensi',
    content: `
      Hipertensi adalah faktor risiko ketiga terbesar yang menyebabkan kematian dini, terjadinya gagal jantung serta penyakit gangguan otak. Hipertensi dikenal sebagai the killer disease dan the heteregeneous group of disease. Penyakit ini telah menjadi masalah utama dalam kesehatan masyarakat di Indonesia dan beberapa negara di dunia. Diperkirakan ± 80% kenaikan kasus hipertensi dari 639 juta pada tahun 2000 akan terjadi di negara berkembang pada tahun 2025.Hipertensi dapat menyerang siapa saja dari berbagai kelompok umur,sosial dan ekonomi. Dengan bertambahnya umur, risiko terkena hipertensi menjadi lebih besar, hal tersebut disebabkan oleh perubahan struktur pada pembuluh darah besar, sehingga lumen menjadi lebih sempit dan dinding pembuluh darah menjadi lebih kaku, sebagai akibatnya tekanan darah sistoli meningkat.Beberapa anjuran dalam upayapenurunan tekanan darah melalui modifikasigaya hidup yaitu dengan penurunan berat badan,penerapan perencanaan makan dengan dietaryapproaches to stop hypertension (DASH), pembatasan asupan garam NaCl, membatasi asupan alcohol dan olah raga teratur mencakup berjalan, jogging, bersepeda, dan berenang setidaknya 30 menit per hari. Tidak hanya itu, upaya pencegahan hipertensi dapat dilakukan dengan pemberian ASI oleh ibu kepada anaknya, pemberian antihipertensi untuk mencegah prehipertensi menjadi hipertensi, dan pemberian imunosupresif kepada para penderita autoimunitas. Bentuk-bentuk pencegahan tersebut masih ada yang pro dan kontra sehingga diperlukan penelitian lebih lanjut mengenai pencegahannya.
    `,
    image: 'https://source.unsplash.com/400x200/?exercise,fitness',
  },
  2: {
    title: 'Hipertensi di Usia Muda',
    content: `
Berdasarkan data Puskesmas Kecamatan Kalideres tahun 2020, proporsi hipertensi berada pada urutan ke 2 dari 10 penyakit terbanyak di Puskesmas Kecamatan Kalideres. Tujuan penelitian ini untuk menganalisis faktor-faktor yang berhubungan dengan dengan kejadian hipertensi pada pasien usia 18-45 tahun di Puskesmas Kecamatan Kalideres. Penelitian ini menggunakan desain Cross Sectional dengan sampel sebanyak 211 orang. Analisis data menggunakan analisis univariat dan bivariat dengan uji Chi Square. Penelitian ini dilakukan pada bulan Mei hingga Juli 2020. Hasil analisis univariat menunjukan bahwa lebih banyak yang mengalami hipertensi (64,9%), umur berisiko (75,4%), jenis kelamin perempuan (51,2%), IMT normal (71,1%) dan tidak ada riwayat hipertensi (64,5%). Terdapat hubungan antara umur (PR= 1,396, 95% CI : 1,044-1,867), Obesitas (PR=1,752, 95% CI : 1,487-2,064) dan riwayat hipertensi (1,686, 95% CI : 1,406-2,021) dengan kejadian hipertensi. Adapun variabel yang tidak berhubungan yaitu jenis kelamin dengan kejadian hipertensi. Untuk mencegah hipertensi, dibutuhkan edukasi tentang hipertensi, tenaga psikolog dan menambah jumlah petugas kesehatan agar program kelas gizi dapat berjalan sesuai dengan jadwal
    `,
    image: 'https://source.unsplash.com/400x200/?healthy,food',
  },
  3: {
    title: 'Patuhi Aturan Obat',
    content: `
      Hipertensi merupakan keadaan seseorang mengalami peningkatan tekanan darah di atas normal. Hipertensi dapat menyebabkan komplikasi yang mengenai berbagai organ seperti jantung, otak, ginjal, mata, dan arteri perifer. Masih sedikit penderita hipertensi yang melakukan pengobatan secara teratur untuk mengontrol tekanan darah. Tujuan penelitian ini mengetahui hubungan kepatuhan minum obat dengan perubahan tekanan darah pada lansia di posyandu lansia Ddesa Tanggung Prigel Kec. Glagah Kab. Lamongan. Desain penelitian ini analitik korelasi dengan pendekatan cross sectional. Metode sampling menggunakan Simple random sampling. Sampel dalam penelitian ini sebanyak 27 orang yaitu sebagian lansia di desa Tanggung Prigel Kecamatan Glagah Kabupaten Lamongan. Variabel penelitian ini adalah variabel independent kepatuhan minum obat hipertensi dan variabel dependent adalah tekanan darah. Data diambil menggunakan kuesioner dan observasi. Setelah ditabulasi data dianalisis dengan menggunakan uji spearman rho dengan α < 0,05. Hasil penelitian menunjukkan kepatuhan minum obat hipertensi responden hampir setengahnya memiliki kepatuhan tinggi yaitu 11 responden (40,7%), tekanan darah responden hampir setengahnya memiliki tekanan darah rendah yaitu 10 responden (37%). Hasil uji spearman rho menunjukkan ρ = 0,004 < α = 0,05 berarti terdapat hubungan kepatuhan minum obat dengan perubahan tekanan darah pada lansia di Desa Tanggung Prigel Kecamatan Glagah Kabupaten Lamongan. Penderita hipertensi hendaknya mematuhi aturan minum obat hipertensi sesuai yang disarankan oleh tenaga kesehatan. Keluarga diharapkan melakukan pemantauan kepada responden dalam kepatuhan mengkonsumsi obat hipertensi setiap harinya. Petugas kesehatan perlu meningkatkan edukasi kepada masyarakat penderita hipertensi agar teratur mengkonsumsi obat anti hipertensi
    `,
    image: 'https://source.unsplash.com/400x200/?balance,lifestyle',
  },
  4: { 
    title: 'Efektivitas Edukasi Kesehatan untuk Pasien Hipertensi',
    content: `
      Penelitian yang dilakukan untuk menilai efektivitas edukasi kesehatan pada pasien hipertensi menunjukkan hasil yang signifikan, di mana peningkatan pengetahuan dan perubahan perilaku menjadi hal yang utama. Penelitian ini dilaksanakan di RSUD Prof. DR. WZ Johannes Kupang, dengan melibatkan pasien rawat jalan yang didiagnosis hipertensi. Hasil penelitian menunjukkan adanya perubahan pengetahuan yang signifikan sebelum dan sesudah intervensi edukasi dengan nilai p = 0,000 yang lebih kecil dari α = 0,005, yang menunjukkan bahwa edukasi kesehatan berpengaruh besar terhadap peningkatan pemahaman pasien.
  
      Sebelum dilakukan edukasi, banyak pasien yang belum sepenuhnya memahami kondisi mereka, khususnya dalam hal tekanan darah normal, gejala yang harus diwaspadai, penyebab hipertensi, serta potensi komplikasi yang dapat muncul jika hipertensi tidak diobati dengan benar. Banyak pasien yang belum menyadari bahwa hipertensi dapat menimbulkan penyakit jantung, stroke, atau gagal ginjal, yang seringkali berakibat fatal.
  
      Program edukasi dilakukan dengan pendekatan yang terstruktur, yakni melalui serangkaian pertemuan rutin sebanyak tiga kali. Setiap pertemuan mengandung materi penting terkait dengan pengelolaan hipertensi. Media yang digunakan untuk menyampaikan informasi meliputi leaflet, video edukasi, dan diskusi interaktif dengan tenaga medis. Media ini dipilih agar pesan dapat disampaikan dengan cara yang mudah dipahami dan dapat diingat oleh pasien. Selain itu, pasien juga diberikan kesempatan untuk bertanya langsung kepada tenaga medis mengenai topik yang mereka kurang pahami.
  
      Hasil dari edukasi ini sangat menggembirakan, karena pasien menunjukkan pemahaman yang lebih baik mengenai pentingnya pola hidup sehat, seperti diet rendah garam, rutin berolahraga, dan memantau tekanan darah secara berkala. Tak hanya itu, pasien juga menjadi lebih terbuka mengenai pengobatan yang mereka jalani, yang berujung pada peningkatan kepatuhan terhadap terapi medis yang dianjurkan.
  
      Faktor lain yang turut memengaruhi efektivitas edukasi ini adalah tingkat pendidikan pasien. Berdasarkan hasil analisis data, pasien yang memiliki tingkat pendidikan lebih tinggi, seperti mereka yang berpendidikan SMA, cenderung menunjukkan peningkatan pengetahuan yang lebih signifikan dibandingkan dengan pasien yang berpendidikan lebih rendah. Hal ini menunjukkan pentingnya pendekatan yang disesuaikan dengan tingkat pemahaman dan pendidikan pasien, sehingga edukasi dapat lebih mudah diterima dan diterapkan dalam kehidupan sehari-hari.
  
      Secara keseluruhan, penelitian ini menunjukkan bahwa edukasi kesehatan yang dilaksanakan secara intensif dan terstruktur dapat memberikan dampak positif yang besar terhadap pengelolaan hipertensi. Dengan meningkatnya pengetahuan, diharapkan pasien dapat lebih sadar akan risiko hipertensi dan lebih proaktif dalam menjaga kesehatan mereka. Edukasi ini menjadi salah satu strategi utama dalam pencegahan dan pengobatan hipertensi, yang pada gilirannya dapat mengurangi angka kematian dan meningkatkan kualitas hidup pasien.
    `,
    image: 'https://source.unsplash.com/400x200/?education,health',
  },
};
export default articles;
